name: ci

on:
  push:

jobs:
  testdocker:
    runs-on: ubuntu-latest
    uses: AgnostiqHQ/covalent-awslambda-plugin/.github/workflows/docker.yml@develop
    secrets: inherit
    with:
      prerelease: true